services:
  server:
    build: ./server
    container_name: server
    ports:
      - "3002:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
